export const projects = [
  {
    number: "01",
    title: "Nutricomp — Marmitas App",
    category: "Front-end",
    description: "Cardápio digital com montagem de combos, carrinho persistente, informações nutricionais e preparação de uma mensagem de pedido para envio pelo WhatsApp.",
    technologies: ["React", "TypeScript", "Tailwind CSS", "Vite"],
    status: "Publicado",
    repositoryUrl: "https://github.com/DescomplicaDevDan/marmitas-app",
    siteUrl: "https://www.nutricomp.com.br",
    featured: true,
  },
  {
    number: "02",
    title: "Motor de Busca",
    category: "Fundamentos técnicos",
    description: "Projeto didático que busca documentos com índice invertido, ordena resultados por relevância com TF-IDF e oferece sugestões de pesquisa usando uma árvore Trie.",
    technologies: ["Python", "Flask", "TF-IDF", "Trie"],
    status: "Projeto didático",
    repositoryUrl: "https://github.com/DescomplicaDevDan/Motor_busca",
    siteUrl: "https://motor-busca.vercel.app/",
    featured: false,
  },
  {
    number: "03",
    title: "Central de Chamados",
    category: "Front-end",
    description: "Central interna de suporte em desenvolvimento, com layout e prévia do formulário de abertura de chamados. Atendimento e acompanhamento de solicitações estão planejados.",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    status: "Em desenvolvimento",
    repositoryUrl: "https://github.com/DescomplicaDevDan/Central-de-Chamados",
    siteUrl: null,
    featured: false,
  },
] as const;
