export const projects = [
  {
    number: "01",
    title: "Nutricomp — Marmitas App",
    category: "Front-end",
    description: "Cardápio digital com montagem de combos, carrinho persistente, informações nutricionais e checkout integrado ao WhatsApp para organizar os pedidos.",
    technologies: ["React", "TypeScript", "Tailwind CSS", "Vite"],
    status: "Publicado",
    repositoryUrl: "https://github.com/DescomplicaDevDan/marmitas-app",
    siteUrl: "https://www.nutricomp.com.br",
    featured: true,
  },
  {
    number: "02",
    title: "Self em Ação",
    category: "Front-end",
    description: "Landing page responsiva para apresentar serviços de psicologia, neuropsicologia e consultoria organizacional, com identidade visual e conteúdo organizados em componentes reutilizáveis.",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    status: "Em desenvolvimento",
    repositoryUrl: "https://github.com/DescomplicaDevDan/self-em-acao",
    siteUrl: null,
    featured: false,
  },
  {
    number: "03",
    title: "Motor de Busca",
    category: "Back-end",
    description: "Projeto didático que busca documentos com índice invertido, ordena resultados por relevância com TF-IDF e oferece sugestões de pesquisa usando uma árvore Trie.",
    technologies: ["Python", "Flask", "TF-IDF", "Trie"],
    status: "Projeto didático",
    repositoryUrl: "https://github.com/DescomplicaDevDan/Motor_busca",
    siteUrl: null,
    featured: false,
  },
] as const;
